version: '3.6'
services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
